# https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action
name: Octopus Playground
description: An Octopus Playground
inputs:
  version:
    description: Version to install
    required: true
runs:
  using: node12
  main: dist/index.js
